odom_node:
  ros__parameters:
    wheel_radius: 0.2
    wheel_base: 0.6
    ticks_per_revolution: 1075

cmd_vel_node:
  ros__parameters:
    wheel_radius: 0.2
    wheel_base: 0.6
    ticks_per_revolution: 1075

motordriver_node:
  ros__parameters:
    simulation: False
      

