motordriver_node:
  ros__parameters:
    simulation: True
odom_node:
  ros__parameters:
    wheel_radius: 0.0345
    wheel_base: 0.212
    ticks_per_revolution: 1000
cmd_vel_node:
  ros__parameters:
    wheel_radius: 0.0345
    wheel_base: 0.212
battery_alert_node:
  ros__parameters:
    threshold: 10.5
battery_republish_node:
  ros__parameters:
    battery_check_interval: 5.0
